config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :new, :create, :destroy ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [ :new, :create, :destroy]
  before_action :set_bookmark, only: [ :destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :movies)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container m-3">
  <h1 class="mb-3">Add a movie to list: <%= @list.name%> </h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container m-3">
  <h1 class="mb-3">my lists</h1>
  <% @lists.each do |l| %>
    <div class="card mb-3">
    <p class="mb-3">
      <%= l.name %>
      <%= link_to "See more", list_path(l)%>
    </p>
    </div>
  <% end %>
  <div class="mb-3">
    <%= link_to "Create a new list", new_list_path %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container m-3">
  <h1 class="mb-3">Create a list</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container m-3">
  <h1 class="mb-3"><%= @list.name %></h1>

  <div class="mb-3 d-flex">
    <% @movies.each do |m| %>
      <div class="card mb-3">
        <p class="mb-3"><%= m.title %></p>
        <p class="mb-3"><%= image_tag(m.poster_url, height: "400px", loading: "lazy") %></p>
        <p class="mb-3"><%= m.overview %></p>
        <p class="mb-3"><%= m.rating %></p>
        <p class="mb-3">
          <%= link_to "Delete from list", list_bookmark_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
        </p>
      </div>
    <% end %>
  </div>
  <p class="mb-3">
    <%= link_to "Add movie", new_list_bookmark_path(@list) %>
  </p>
  <p class="mb-3">
    <%= link_to "Back to list index", lists_path %>
  </p>
</div>